/// <reference types="@cloudflare/workers-types/2023-07-01" />
// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	DLER_EMAIL: string;
	DLER_PASSWORD: string;
}
